version: "2"
services:
  linux-x64:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${BASE}:/work
      - ./entrypoint.sh:/entrypoint.sh
      - ../../docker-ve-root.sh:/docker-ve-root.sh
      - ./.bash_history:/root/.bash_history
      - /tmp:/tmp
      - /proc:/proc
    environment:
      - CC=
      - CXX=
      - CROSS_TRIPLE=
      - AR=
      - AS=
    hostname: ve-root
    entrypoint: /entrypoint.sh
    stdin_open: true
    tty: true

